# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
 - &filter-only-master
   branches:
     only:
       - master

version: 2.1
jobs:
  deploy-website:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "66:90:61:3b:7c:e9:c2:1f:b6:82:10:d7:cd:97:0e:01"
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "engineering@terra.money"
            git config --global user.name "Terra Engineering"
            yarn install && GIT_USER=YunSuk-Yeo ./deploy.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
        filters: *filter-only-master