name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
      - name: Sphinx Docs build with ReadTheDocs Docker
        uses: DavidLeoni/readthedocs-to-actions@v1.2
        with:
          docs-folder: "."

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build/html
          GIT_CONFIG_NAME: Github Actions
          GIT_CONFIG_EMAIL: noreply@github.com
