name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          yarn
          yarn build
          echo 'docs.terra.money' > docs/.vuepress/dist/CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          GIT_CONFIG_NAME: Github Actions
          GIT_CONFIG_EMAIL: noreply@github.com
